language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
      - cmake
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - libwayland-dev
      - libxkbcommon-dev
      - libegl1-mesa-dev
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true